### ISSUE TITLE
Typo on the readme

### ISSUE THREAD

**Issue by binyamindavid** [galulex/customize.css#4]
I think there is a typo on the read me.

``` ruby
$inputs: (
  border: 3px solid red;
);
```

It should be 

``` ruby
$inputs: (
  border: 3px solid red
);

```

**Comment by galulex** [comment]
@benjaminsigidi Good catch

**Comment by galulex** [comment]
https://github.com/galulex/customize.css/commit/4ca757e7d0e5834cc2f1dfc90bb9eebf849af5ab
